### ISSUE TITLE
aws-lc-sys fails to compile on iOS arm64 with Clang 15.0.7: undeclared ioctl in urandom.c

### ISSUE THREAD

**Issue by thenextman** [aws/aws-lc-rs#1068]
### Problem:

GitHub macos-14 runners recently upgraded system clang from 15.0.0 to 15.0.7 and this directly correlates with a failure to build targetting `aarch64-apple-io`.   This was previously reported and fixed for NetBSD in #932, but the fix presumably did not cover iOS. The bug affects all recent `aws-lc-sys` versions (confirmed on 0.37.1 and 0.38.0).

### Build error

aws-lc-sys: /path/to/aws-lc-sys-0.38.0/aws-lc/crypto/rand_extra/urandom.c:370:9: error: call to undeclared function 'ioctl'; ISO C99 and later do not support implicit function declarations [-Werror,-Wimplicit-function-declaration]
aws-lc-sys: /path/to/aws-lc-sys-0.38.0/aws-lc/crypto/rand_extra/urandom.c:370:27: error: use of undeclared identifier 'RNDGETENTCNT'

### Environment
 - Target: `aarch64-apple-ios`
 - Clang: 15.0.7 (system, not Homebrew)
 - Host: `aarch64-apple-darwin` (macOS 14, GitHub Actions `macos-14-arm64` runner image `20260317.0174`)
 - `aws-lc-sys`: 0.37.1 and 0.38.0 (both affected)
 - Builder: CC (not CMake)

### Root cause

`urandom.c` calls `ioctl(urandom_fd, RNDGETENTCNT, &entropy_bits)`. `RNDGETENTCNT` is a Linux-specific constant defined in `<linux/random.h>` that does not exist on Darwin. `ioctl` itself exists on iOS/macOS but is not declared in scope because `<sys/ioctl.h>` is not included.                                                                                                                                                                                                                  

### Expected behavior

The `ioctl`/`RNDGETENTCNT` code path should be excluded on non-Linux targets, either by adding `#include <sys/ioctl.h>` with an appropriate `#ifdef __linux__` guard

**Comment by justsmth** [comment]
Hello!  Sorry about this build failure.

**** As a workaround, you might try setting something like`CFLAGS="-DOPENSSL_IOS="` in the build environment. **** 

I'm trying to trace the root cause for this... 

1) We're failing to pick up `OPENSSL_RAND_CCRANDOMGENERATEBYTES` [here](https://github.com/aws/aws-lc/blob/main/crypto/rand_extra/internal.h#L18-L22), and falling through to pick up `OPENSSL_RAND_URANDOM`.
```
#elif defined(OPENSSL_IOS)
#define OPENSSL_RAND_CCRANDOMGENERATEBYTES
#else
#define OPENSSL_RAND_URANDOM
#endif
```
Why isn't `OPENSSL_IOS` defined?

2) We should be picking up the definition of `OPENSSL_IOS` [here](https://github.com/aws/aws-lc/blob/main/include/openssl/target.h#L96-L98), but we're missing it.
```
#if defined(TARGET_OS_IPHONE) && TARGET_OS_IPHONE
#define OPENSSL_IOS
#endif
```
Why isn't `TARGET_OS_IPHONE` defined?

3) The `TARGET_OS_IPHONE` definition should be coming from  "`TargetConditionals.h" which is included in "base.h" [here](https://github.com/aws/aws-lc/blob/main/include/openssl/base.h#L23-L25)
```
#if defined(__APPLE__)
#include <TargetConditionals.h>
#endif
```

4) So, why isn't "TargetConditionals.h" providing `TARGET_OS_IPHONE`? 

```
¯\_(ツ)_/¯
```

Do you any other logging from the build output?

 I'll also see if I can reproduce, and have it fixed on our main branch soon.

**Comment by justsmth** [comment]
Update: I was able to reproduce: https://github.com/aws/aws-lc-rs/actions/runs/23320273416/job/67829828359#step:5:1

I'll dig in to it tomorrow. Thanks for letting us know about this!

**Comment by thenextman** [comment]
Hi! I had _thought_ that was related to the clang upgrade, but now I'm not so sure. I can definitely say that this broke "overnight" and I think the only change must've been on the GitHub runner...

Since you can reproduce it, I'll leave it with you. Thank you sincerely for the fast response and attention!

**Comment by thenextman** [comment]
@justsmth In the end this looks like a purely GitHub issue, as our builds magically fixed themselves today. There is some chatter about the latest images incorrectly using homebrew clang instead of Xcode clang: https://github.com/actions/runner-images/issues/13829

I don't know if GitHub yanked the latest image, or we just got "lucky" and starting pulling an older image.

**Comment by justsmth** [comment]
> ... In the end this looks like a purely GitHub issue, as our builds magically fixed themselves today. ...

🎉 I'm glad the problem has been mitigated in the runner image!

I do think this is an edge-case that should be handled better in AWS-LC. I'll try to push through the PR to mitigate this upstream, just to avoid any future problems were the GitHub runner ever to regress.

**Comment by justsmth** [comment]
Hello!  Yesterday, we released [`aws-lc-rs` v1.16.3](https://github.com/aws/aws-lc-rs/releases/tag/v1.16.3) and `aws-lc-sys` v0.40.0, which has the [upstream change](https://github.com/aws/aws-lc/pull/3113) that addresses this issue.

This issue will now be closed.  Feel free to comment here or open another issue if you continue to have problems after upgrading.  Thanks for your help with improving our library! 😄
